name: locuslab
description: A Locus experiences collection
version: 1.0.0+8
publish_to: 'none'

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  locus:
    path: ../
  
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons_maker: ^0.10.2

flutter_icons:
  android: true
  ios: true
  macos: true
  image_path: assets/icon.png

flutter:
  uses-material-design: false
