name: locus
description: Design system built for Parabola
version: 0.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-ExtraLight.otf
          weight: 200
        - asset: fonts/Manrope-Light.otf
          weight: 300
        - asset: fonts/Manrope-Regular.otf
          weight: 400
        - asset: fonts/Manrope-Medium.otf
          weight: 500
        - asset: fonts/Manrope-SemiBold.otf
          weight: 600
        - asset: fonts/Manrope-Bold.otf
          weight: 700
        - asset: fonts/Manrope-ExtraBold.otf
          weight: 700
